name: Main workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node: ['10']
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
        env:
          GH_ACTION_DEPLOY_KEY: ${{secrets.GH_ACTION_DEPLOY_KEY}}
      - run: |
          mkdir -p ~/.ssh/
          echo "$GH_ACTION_DEPLOY_KEY" > ~/runner/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/runner/.ssh/known_hosts
          git config --global user.name 'rxliuli'
          git config --global user.email 'rxliuli@gmail.com'
      - run: yarn
      - run: yarn deploy
